/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: ../studio/schema.json
export type VideoSettings = {
  autoplay?: boolean;
  controls?: boolean;
};

export type SiteCookieBanner = {
  _id: string;
  _type: "siteCookieBanner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  useCookieBanner?: boolean;
  consentModal?: {
    description?: string;
    acceptAllBtn?: string;
    acceptNecessaryBtn?: string;
    showPreferencesBtn?: string;
  };
  preferencesModal?: {
    title?: string;
    acceptAllBtn?: string;
    acceptNecessaryBtn?: string;
    savePreferencesBtn?: string;
    sections?: Code;
  };
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type ErrorSettings = {
  _id: string;
  _type: "errorSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  notFoundTitle: InternationalizedArrayString;
  notFoundBody?: InternationalizedArrayRichText;
  serverErrorTitle: InternationalizedArrayString;
  serverErrorBody?: InternationalizedArrayRichText;
};

export type InternationalizedArrayRichText = Array<
  {
    _key: string;
  } & InternationalizedArrayRichTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type SiteNav = {
  _id: string;
  _type: "siteNav";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  mainMenu?: Array<
    | ({
        _key: string;
      } & Link)
    | ({
        _key: string;
      } & NavLanguageSwitch)
  >;
  footerMenu?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type SiteLanguageSettings = {
  _id: string;
  _type: "siteLanguageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  availableLanguages: Array<{
    id: string;
    title: string;
    _type: "siteLanguage";
    _key: string;
  }>;
  defaultLanguageId: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: SeoFallback;
};

export type SeoFallback = {
  _type: "seo.fallback";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type RichTextMedia = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ModuleMedia)
  | ({
      _key: string;
    } & ModuleCarousel)
>;

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4";
  listItem?: "bullet" | "number";
  markDefs?: Array<
    {
      _key: string;
    } & Link
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ModuleText = {
  _type: "module.text";
  title: InternationalizedArrayString;
  body?: InternationalizedArrayRichTextMedia;
};

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type ModuleContentRefs = {
  _type: "module.contentRefs";
  heading?: InternationalizedArrayString;
  allowMultiple?: boolean;
  reference?: HomeReference | PageReference;
  references?: ArrayOf<HomeReference | PageReference>;
};

export type ModuleMedia = {
  _type: "module.media";
  type: "image" | "video";
  imageContent?: MediaImage;
  videoContent?: MediaVideo;
};

export type ModuleCarousel = {
  _type: "module.carousel";
  heading?: InternationalizedArrayString;
  imagesOnly?: boolean;
  slides?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  slidesMedia?: Array<
    {
      _key: string;
    } & ModuleMedia
  >;
};

export type MediaVideo = {
  _type: "media.video";
  video?: MuxVideo;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoSettings?: VideoSettings;
  caption?: string;
};

export type MediaImage = {
  _type: "media.image";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
};

export type NavLanguageSwitch = {
  _type: "nav.languageSwitch";
  blockKind?: string;
};

export type Link = {
  _type: "link";
  type: "internal" | "external" | "function";
  title?: string;
  reference?: HomeReference | PageReference;
  url?: string;
  blank?: boolean;
  func?: LinkFunctions;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: InternationalizedArrayString;
  slug: Slug;
  modules?: Array<
    | ({
        _key: string;
      } & ModuleMedia)
    | ({
        _key: string;
      } & ModuleCarousel)
    | ({
        _key: string;
      } & ModuleContentRefs)
    | ({
        _key: string;
      } & ModuleText)
  >;
  seo?: SeoPage;
};

export type SeoPage = {
  _type: "seo.page";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: InternationalizedArrayString;
  modules?: Array<
    | ({
        _key: string;
      } & ModuleMedia)
    | ({
        _key: string;
      } & ModuleCarousel)
    | ({
        _key: string;
      } & ModuleContentRefs)
    | ({
        _key: string;
      } & ModuleText)
  >;
  seo?: SeoPage;
};

export type InternationalizedArrayRichTextMedia = Array<
  {
    _key: string;
  } & InternationalizedArrayRichTextMediaValue
>;

export type LinkFunctions = {
  _type: "linkFunctions";
  key: "scroll-to" | "open-modal";
  params?: string;
};

export type InternationalizedArrayRichTextMediaValue = {
  _type: "internationalizedArrayRichTextMediaValue";
  value?: RichTextMedia;
  language: string;
};

export type InternationalizedArrayRichTextValue = {
  _type: "internationalizedArrayRichTextValue";
  value?: RichText;
  language: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language: string;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | VideoSettings
  | SiteCookieBanner
  | Code
  | ErrorSettings
  | InternationalizedArrayRichText
  | InternationalizedArrayString
  | SiteNav
  | SiteLanguageSettings
  | SanityImageAssetReference
  | SiteSettings
  | SeoFallback
  | SanityImageCrop
  | SanityImageHotspot
  | RichTextMedia
  | RichText
  | ModuleText
  | HomeReference
  | PageReference
  | ModuleContentRefs
  | ModuleMedia
  | ModuleCarousel
  | MediaVideo
  | MediaImage
  | NavLanguageSwitch
  | Link
  | Page
  | SeoPage
  | Slug
  | Home
  | InternationalizedArrayRichTextMedia
  | LinkFunctions
  | InternationalizedArrayRichTextMediaValue
  | InternationalizedArrayRichTextValue
  | InternationalizedArrayStringValue
  | MuxVideoAssetReference
  | MuxVideo
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/snippets/settings.ts
// Variable: siteLanguageSettingsQuery
// Query: *[_id == "siteLanguageSettings"][0]{  _id,  availableLanguages[]{id, title},  defaultLanguageId}
export type SiteLanguageSettingsQueryResult =
  | {
      _id: "siteLanguageSettings";
      availableLanguages: Array<{
        id: string;
        title: string;
      }>;
      defaultLanguageId: string;
    }
  | {
      _id: "siteLanguageSettings";
      availableLanguages: null;
      defaultLanguageId: null;
    }
  | null;

// Source: sanity/queries/snippets/settings.ts
// Variable: siteSettingsTitleQuery
// Query: *[_id == "siteSettings"][0]{title}
export type SiteSettingsTitleQueryResult =
  | {
      title: InternationalizedArrayString;
    }
  | {
      title: null;
    }
  | {
      title: string;
    }
  | {
      title: string | null;
    }
  | null;

// Source: sanity/queries/snippets/settings.ts
// Variable: siteSettingsSeoFallbackQuery
// Query: *[_id == "siteSettings"][0]{  "title": seo.title,  "description": seo.description,  "imageUrl": seo.image.asset->url}
export type SiteSettingsSeoFallbackQueryResult =
  | {
      title: null;
      description: null;
      imageUrl: null;
    }
  | {
      title: string | null;
      description: string | null;
      imageUrl: string | null;
    }
  | null;

// Source: sanity/queries/snippets/sitemap.ts
// Variable: pageSlugsQuery
// Query: *[_type == "page" && defined(slug.current)]{  "slug": slug.current}
export type PageSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: sanity/queries/snippets/sitemap.ts
// Variable: sitemapPagesQuery
// Query: *[_type == "home" || (_type == "page" && defined(slug.current))]{  _id,  _type,  _updatedAt,  "slug": select(_type == "home" => null, slug.current),  "path": select(_type == "home" => "/", "/" + slug.current)}
export type SitemapPagesQueryResult = Array<
  | {
      _id: string;
      _type: "home";
      _updatedAt: string;
      slug: null;
      path: "/";
    }
  | {
      _id: string;
      _type: "page";
      _updatedAt: string;
      slug: string;
      path: string;
    }
>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_id == "siteLanguageSettings"][0]{\n  _id,\n  availableLanguages[]{id, title},\n  defaultLanguageId\n}': SiteLanguageSettingsQueryResult;
    '*[_id == "siteSettings"][0]{title}': SiteSettingsTitleQueryResult;
    '*[_id == "siteSettings"][0]{\n  "title": seo.title,\n  "description": seo.description,\n  "imageUrl": seo.image.asset->url\n}': SiteSettingsSeoFallbackQueryResult;
    '*[_type == "page" && defined(slug.current)]{\n  "slug": slug.current\n}': PageSlugsQueryResult;
    '*[_type == "home" || (_type == "page" && defined(slug.current))]{\n  _id,\n  _type,\n  _updatedAt,\n  "slug": select(_type == "home" => null, slug.current),\n  "path": select(_type == "home" => "/", "/" + slug.current)\n}': SitemapPagesQueryResult;
  }
}
