/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type VideoSettings = {
  autoplay?: boolean;
  controls?: boolean;
};

export type SiteLanguageSettings = {
  _id: string;
  _type: "siteLanguageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  availableLanguages: Array<{
    id: string;
    title: string;
    _type: "siteLanguage";
    _key: string;
  }>;
  defaultLanguageId: string;
};

export type RichTextMedia = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ModuleMedia)
  | ({
      _key: string;
    } & ModuleCarousel)
>;

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4";
  listItem?: "bullet" | "number";
  markDefs?: Array<
    {
      _key: string;
    } & Link
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ModuleText = {
  _type: "module.text";
  title: string;
  body?: RichTextMedia;
};

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type ModuleContentRefs = {
  _type: "module.contentRefs";
  heading?: string;
  allowMultiple?: boolean;
  reference?: HomeReference | PageReference;
  references?: ArrayOf<HomeReference | PageReference>;
};

export type ModuleMedia = {
  _type: "module.media";
  type: "image" | "video";
  imageContent?: MediaImage;
  videoContent?: MediaVideo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ModuleCarousel = {
  _type: "module.carousel";
  heading?: string;
  imagesOnly?: boolean;
  slides?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  slidesMedia?: Array<
    {
      _key: string;
    } & ModuleMedia
  >;
  loop?: boolean;
  showThumbnails?: boolean;
  showNavDots?: boolean;
  autoplay?: boolean;
  autoplayDelayMs?: number;
};

export type MediaVideo = {
  _type: "media.video";
  video?: MuxVideo;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoSettings?: VideoSettings;
  caption?: string;
};

export type MediaImage = {
  _type: "media.image";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
};

export type NavLanguageSwitch = {
  _type: "nav.languageSwitch";
  blockKind?: string;
};

export type Link = {
  _type: "link";
  type: "internal" | "external" | "function";
  title?: string;
  reference?: HomeReference | PageReference;
  url?: string;
  blank?: boolean;
  func?: LinkFunctions;
};

export type SeoFallback = {
  _type: "seo.fallback";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SeoPage = {
  _type: "seo.page";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LinkFunctions = {
  _type: "linkFunctions";
  key: "scroll-to" | "open-modal";
  params?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type ErrorSettingsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "errorSettings";
};

export type SiteNavReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteNav";
};

export type SiteSettingsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteSettings";
};

export type SiteCookieBannerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteCookieBanner";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | HomeReference
    | PageReference
    | ErrorSettingsReference
    | SiteNavReference
    | SiteSettingsReference
    | SiteCookieBannerReference;
  language: string;
};

export type SiteCookieBanner = {
  _id: string;
  _type: "siteCookieBanner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  useCookieBanner?: boolean;
  consentModal?: {
    description?: string;
    acceptAllBtn?: string;
    acceptNecessaryBtn?: string;
    showPreferencesBtn?: string;
  };
  preferencesModal?: {
    title?: string;
    acceptAllBtn?: string;
    acceptNecessaryBtn?: string;
    savePreferencesBtn?: string;
    sections?: Code;
  };
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title: string;
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: SeoFallback;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SiteNav = {
  _id: string;
  _type: "siteNav";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  mainMenu?: Array<
    | ({
        _key: string;
      } & Link)
    | ({
        _key: string;
      } & NavLanguageSwitch)
  >;
  footerMenu?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type ErrorSettings = {
  _id: string;
  _type: "errorSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  notFoundTitle: string;
  notFoundBody?: RichText;
  serverErrorTitle: string;
  serverErrorBody?: RichText;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title: string;
  slug: Slug;
  modules?: Array<
    | ({
        _key: string;
      } & ModuleMedia)
    | ({
        _key: string;
      } & ModuleCarousel)
    | ({
        _key: string;
      } & ModuleContentRefs)
    | ({
        _key: string;
      } & ModuleText)
  >;
  seo?: SeoPage;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title: string;
  modules?: Array<
    | ({
        _key: string;
      } & ModuleMedia)
    | ({
        _key: string;
      } & ModuleCarousel)
    | ({
        _key: string;
      } & ModuleContentRefs)
    | ({
        _key: string;
      } & ModuleText)
  >;
  seo?: SeoPage;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | VideoSettings
  | SiteLanguageSettings
  | RichTextMedia
  | RichText
  | ModuleText
  | HomeReference
  | PageReference
  | ModuleContentRefs
  | ModuleMedia
  | SanityImageAssetReference
  | ModuleCarousel
  | MediaVideo
  | MediaImage
  | NavLanguageSwitch
  | Link
  | SeoFallback
  | SeoPage
  | LinkFunctions
  | TranslationMetadata
  | InternationalizedArrayReference
  | ErrorSettingsReference
  | SiteNavReference
  | SiteSettingsReference
  | SiteCookieBannerReference
  | InternationalizedArrayReferenceValue
  | SiteCookieBanner
  | Code
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SiteNav
  | ErrorSettings
  | Page
  | Slug
  | Home
  | MuxVideoAssetReference
  | MuxVideo
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
