name: PR Slack notify

on:
  pull_request_target:
    types: [opened, ready_for_review, closed]
    branches:
      - main
      - variant/document-level

jobs:
  notify:
    uses: backendforth/.github/.github/workflows/pr-slack-summary.yml@main
    secrets: inherit
