import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  plugins: [],
  theme: {
    extend: {
      screens: {
        min: "375px",
        xs: "680px",
        sm: "780px",
        md: "1180px",
        lg: "1280px",
        xl: "1440px",
        max: "1600px",
      },
      borderRadius: {
        DEFAULT: "2rem",
      },
      borderWidth: {
        DEFAULT: ".0625rem",
        0: "0",
      },
      fontFamily: {
        sans: ["var(--font-dm-sans)", "Helvetica", "Arial", "sans-serif"],
        serif: ["Georgia", "serif"],
        mono: ["var(--font-geist-mono)", "Courier New", "monospace"],
      },
      colors: {
        current: "currentColor",
        transparent: "transparent",
        white: "var(--white)",
        black: "var(--black)",
        grey: "var(--grey)",
        red: "var(--red)",
        orange: "var(--orange)",
        yellow: "var(--yellow)",
        darkBlue: "var(--darkBlue)",
        lightBlue: "var(--lightBlue)",
        pink: "var(--pink)",
        coral: "var(--coral)",
        raspberry: "var(--raspberry)",
        rose: "var(--rose)",

        brandColor: "var(--brandColor)",
        accentColor: "var(--accentColor)",

        textColor: "var(--textColor)",
        textMuted: "var(--textMuted)",
        headingColor: "var(--headingColor)",
        linkColor: "var(--linkColor)",
        linkDecoration: "var(--linkDecoration)",
        linkDecorationHover: "var(--linkDecorationHover)",
        hoverColor: "var(--hoverColor)",
        activeColor: "var(--activeColor)",

        bgColor: "var(--bgColor)",
        surfaceMuted: "var(--surfaceMuted)",
        borderSubtle: "var(--borderSubtle)",
        codeBg: "var(--codeBg)",
        codeText: "var(--codeText)",

        error: "var(--errorColor)",
        success: "var(--successColor)",
        danger: "var(--dangerColor)",

        /* shadcn / radix-ui semantic aliases */
        background: "var(--bgColor)",
        foreground: "var(--textColor)",
        primary: "var(--brandColor)",
        "primary-foreground": "var(--white)",
        secondary: "var(--surfaceMuted)",
        "secondary-foreground": "var(--textColor)",
        muted: "var(--surfaceMuted)",
        "muted-foreground": "var(--textMuted)",
        accent: "var(--surfaceMuted)",
        "accent-foreground": "var(--textColor)",
        destructive: "var(--dangerColor)",
        "destructive-foreground": "var(--white)",
        border: "var(--borderSubtle)",
        input: "var(--borderSubtle)",
        ring: "var(--accentColor)",
      },
      aspectRatio: {
        "4/3": "4 / 3",
        "3/4": "3 / 4",
        "2/1": "2 / 1",
      },
      brightness: {
        70: ".70",
      },
      height: {
        min: "var(--size-min)",
        xs: "var(--size-xs)",
        sm: "var(--size-sm)",
        md: "var(--size-md)",
        lg: "var(--size-lg)",
        xl: "var(--size-xl)",
        max: "var(--size-max)",
        extra: "var(--size-extra)",
      },
      width: {
        min: "var(--size-min)",
        xs: "var(--size-xs)",
        sm: "var(--size-sm)",
        md: "var(--size-md)",
        lg: "var(--size-lg)",
        xl: "var(--size-xl)",
        max: "var(--size-max)",
        extra: "var(--size-extra)",
        containerGutter: "var(--container-gutter)",
      },
      spacing: {
        min: "var(--size-min)",
        xs: "var(--size-xs)",
        sm: "var(--size-sm)",
        md: "var(--size-md)",
        lg: "var(--size-lg)",
        xl: "var(--size-xl)",
        max: "var(--size-max)",
        extra: "var(--size-extra)",
        navBar: "var(--navBarHeight)",
        containerGutter: "var(--container-gutter)",
      },
      button: {
        primary: {
          DEFAULT: "var(--black)",
          hover: "var(--grey)",
          active: "var(--grey)",
          text: "var(--white)",
        },
      },
    },
  },
} satisfies Config;
